# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
